#!/bin/zsh
exec 2>&1

set -e

source ../../lib/check-dependency
check_dependency rpcstatd

pipefs=/var/lib/nfs/rpc_pipefs
if ! mountpoint -q "$pipefs"; then
    mkdir -p "$pipefs"
    mount -t rpc_pipefs -o defaults rpc_pipefs "$pipefs"
fi

if ! mountpoint -q /proc/fs/nfsd; then
	mount -t nfsd nfsd /proc/fs/nfsd
fi

exportfs -ra > /dev/null
rpc.nfsd
sm-notify

exec rpc.mountd --foreground
