#!/bin/zsh
exec 2>&1

set -e

v4_only=1
mountd_args=( --foreground )
nfsd_args=( )

if [[ $v4_only == 0 ]]; then
    source ../../lib/check-dependency
    check_dependency rpcstatd

    pipefs=/var/lib/nfs/rpc_pipefs
    if ! mountpoint -q "$pipefs"; then
        mkdir -p "$pipefs"
        mount -t rpc_pipefs -o defaults rpc_pipefs "$pipefs"
    fi
else
    nfsd_args=( $nfsd_args -N3 -V4 )
    mountd_args=( $mountd_args -N2 -N3 -V4 )
fi

if ! mountpoint -q /proc/fs/nfsd; then
	mount -t nfsd nfsd /proc/fs/nfsd
fi

exportfs -ra > /dev/null
rpc.nfsd $nfsd_args
sm-notify

exec rpc.mountd $mountd_args
